### ISSUE TITLE
ReferenceError: Module is not defined

### ISSUE THREAD

**Issue by tiancaipipi110** [mykle1/MMM-EyeCandy#2]
Run with command `node  MMM-EyeCandy.js`
I got error:
```
ReferenceError: Module is not defined
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-EyeCandy/MMM-EyeCandy.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

**Comment by mykle1** [comment]
I'm sorry that you're having an issue but the module works as expected here. Perhaps there is a conflict with another module. Please bring the issue to the forum where it would be easier for me to help you
